-- READY-TO-APPLY DRAFT — CC-3 has no migration lane (verify-migration-lane-band.mjs: cc-3/ = chrome-
-- only, authorMigrations:false). Renumber to a claimed slot on origin/main's db/migrations/
-- CLAIMED-MIGRATION-NUMBERS.json before authoring as a real file, per that registry's own
-- "_how_to_claim". OWNER RULING 2026-09-06 (TOUR-SPLIT-PLAN Q3): "DO IT, and it's the gating
-- item... Author it idempotent / CREATE-only (ADD COLUMN IF NOT EXISTS, nullable text)... Migration-
-- lane assignment: CC-1 should author it as the first step of the split, one author per migration."
--
-- WHAT THIS MIGRATION DOES: adds ONE additive, nullable column to
-- driver_finance.driver_settlements: source_document_ref text NULL.
--
-- docs/audit/TOUR-SPLIT-PLAN-2026-09-06.md (§1a) found that `display_id` (S-13642, S-13654, …) is
-- generated by presettlement-link.service.ts's allocateNextSettlementDisplayId, which draws from
-- the SAME shared LOAD/`S-` counter dispatch/load-id-reservation.service.ts's
-- allocateNextLoadNumber uses for load numbers — an explicit prior decision (PS2: "No settlement
-- doc type in lib.trace_counters... one convention with LD/LOAD") that rules out repointing
-- display_id to read a signed settlement number (5769, 5772, … 5787) without colliding with that
-- counter. The signed numbers currently live ONLY in a spreadsheet ("USMCA BY LOAD" sheet) and the
-- plan doc — source_document_ref is the durable, queryable home for them, alongside display_id,
-- never replacing it.
--
-- IDEMPOTENT: ADD COLUMN IF NOT EXISTS — a pure additive DDL, safe to re-run.
-- FRESH-DB SAFE: guarded by to_regclass so a fresh CI DB before this table exists is a clean no-op.
-- NO RLS/GRANT CHANGE: driver_finance.driver_settlements already carries FORCED RLS + standard
-- grants that cover every column on the table (no per-column grant needed).
-- NO UNIQUENESS CONSTRAINT added here (deliberately, per the owner's literal "nullable text"
-- instruction and to avoid blocking the backfill on an as-yet-unverified assumption of exactly one
-- row per signed number) — a future partial unique index
-- (source_document_ref) WHERE source_document_ref IS NOT NULL) can be added once the backfill
-- below has run and is confirmed collision-free; that is a SEPARATE, later migration, not this one.
--
-- BACKFILL (owner ruling: "backfill the 17 numbers through the service layer, never DELETE") is
-- NOT part of this migration — it is a real service-layer write (an UPDATE through whatever
-- settlement-update service function exists once this column is queryable, never a raw SQL
-- UPDATE), scoped to docs/audit/TOUR-SPLIT-PLAN-2026-09-06.md's own mapping (§1's table), and
-- gated the SAME way `scripts/ops/split-seed-tours.ts --apply` already is: the lead's ✔ quoted
-- verbatim. That backfill script is prepared separately once this column exists to test against
-- (CC-3, on request — this repo's "never raw SQL for a financial write" law means the backfill code
-- cannot be written against a column that does not exist yet without being unverifiable).

DO $$
BEGIN
  IF to_regclass('driver_finance.driver_settlements') IS NOT NULL THEN
    ALTER TABLE driver_finance.driver_settlements
      ADD COLUMN IF NOT EXISTS source_document_ref text NULL;
  END IF;
END $$;
