-- CLAIM-RESERVE 202613820000 (merged #20883).
--
-- WHAT THIS MIGRATION DOES: adds ONE additive, nullable column to
-- driver_finance.driver_settlements: source_document_ref text NULL.
--
-- ROUND 10 (owner ruling on TOUR-SPLIT-PLAN-2026-09-06.md's Q3): "DO IT, and it's the gating
-- item... Author it idempotent / CREATE-only (ADD COLUMN IF NOT EXISTS, nullable text)... Migration-
-- lane assignment: CC-1 should author it as the first step of the split, one author per migration."
-- Authored from docs/audit/migration-drafts/SOURCE-DOCUMENT-REF-migration-draft.sql verbatim
-- (CC-3's ready draft; CC-3 has no migration lane per verify-migration-lane-band.mjs).
--
-- docs/audit/TOUR-SPLIT-PLAN-2026-09-06.md (§1a) found that `display_id` (S-13642, S-13654, …) is
-- generated by presettlement-link.service.ts's allocateNextSettlementDisplayId, which draws from
-- the SAME shared LOAD/`S-` counter dispatch/load-id-reservation.service.ts's
-- allocateNextLoadNumber uses for load numbers — an explicit prior decision (PS2: "No settlement
-- doc type in lib.trace_counters... one convention with LD/LOAD") that rules out repointing
-- display_id to read a signed settlement number (5769, 5772, … 5787) without colliding with that
-- counter. The signed numbers currently live ONLY in a spreadsheet ("USMCA BY LOAD" sheet) and the
-- plan doc — source_document_ref is the durable, queryable home for them, alongside display_id,
-- never replacing it.
--
-- IDEMPOTENT: ADD COLUMN IF NOT EXISTS — a pure additive DDL, safe to re-run.
-- FRESH-DB SAFE: guarded by to_regclass so a fresh CI DB before this table exists is a clean no-op.
-- NO RLS/GRANT CHANGE: driver_finance.driver_settlements already carries FORCED RLS + standard
-- grants that cover every column on the table (no per-column grant needed).
-- NO UNIQUENESS CONSTRAINT added here (deliberately, per the owner's literal "nullable text"
-- instruction and to avoid blocking the backfill on an as-yet-unverified assumption of exactly one
-- row per signed number) — a future partial unique index
-- (source_document_ref) WHERE source_document_ref IS NOT NULL) can be added once the backfill
-- below has run and is confirmed collision-free; that is a SEPARATE, later migration, not this one.
--
-- BACKFILL is NOT part of this migration — it is a real service-layer write
-- (apps/backend/src/driver-finance/settlement-source-document-ref.service.ts's
-- setSettlementSourceDocumentRef, called from scripts/ops/backfill-source-document-ref.mjs),
-- scoped to the 10 "KEEP" rows in docs/audit/TOUR-SPLIT-PLAN-2026-09-06.md §1's mapping table —
-- the 7 signed numbers proposed as brand-new settlement rows are OUT OF SCOPE here (that is the
-- actual tour split, gated behind the lead's ✔ per scripts/ops/split-seed-tours.ts's own header).

DO $$
BEGIN
  IF to_regclass('driver_finance.driver_settlements') IS NOT NULL THEN
    ALTER TABLE driver_finance.driver_settlements
      ADD COLUMN IF NOT EXISTS source_document_ref text NULL;
  END IF;
END $$;
