import type { FastifyInstance } from "fastify";
import { registerCustomerRoutes } from "./customers.routes.js";
import { registerCustomerFinancialSummaryRoutes } from "./customer-financial.routes.js";
import { registerCustomerInvoicesRoutes } from "./customer-invoices.routes.js";
import { registerDriversBulkRoutes } from "../drivers/drivers-bulk.routes.js";
import { registerDriverRoutes } from "./drivers.routes.js";
import { registerDriverLabelsRoutes } from "./driver-labels.routes.js";
import { registerDriverTagsRoutes } from "./driver-tags.routes.js";
import { registerDriversImportRoutes } from "./drivers-import.routes.js";
import { registerDriverHireDateApplyRoutes } from "./driver-hire-date-apply.routes.js";
import { registerMdataAccountsRoutes } from "./accounts.routes.js";
import { registerDriverTeamRoutes } from "./driver-teams.routes.js";
import { registerDriverTeamSplitRoutes } from "./driver-team-split.routes.js";
import { registerEquipmentLogRoutes } from "./equipment-log.routes.js";
import { registerEquipmentRoutes } from "./equipment.routes.js";
import { registerEquipmentTransferRoutes } from "./equipment-transfer.routes.js";
import { registerMdataItemsRoutes } from "./items.routes.js";
import { registerLocationRoutes } from "./locations.routes.js";
import { registerLoadRoutes } from "./loads.routes.js";
import { registerLoadAbandonmentRoutes } from "./load-abandonment.routes.js";
import { registerCustomerBulkRoutes } from "./customers-bulk.routes.js";
import { registerEquipmentBulkUpdateRoutes } from "./equipment-bulk-update.routes.js";
import { registerUnitBulkUpdateRoutes } from "./unit-bulk-update.routes.js";
import { registerVendorBulkRoutes } from "./vendors-bulk.routes.js";
import { registerUnitsRoutes } from "./units.routes.js";
import { registerVendorRoutes } from "./vendors.routes.js";
import { registerVendorPaymentMethodRoutes } from "./vendor-payment-methods.routes.js";
import { registerVendorRollupsRoutes } from "./vendor-rollups.routes.js";
import { registerCustomerFinanceRollupRoutes } from "./customer-finance-rollup.routes.js";
import { warmYardBiasCoordinates } from "./yard-location.service.js";

export async function registerMdataRoutes(app: FastifyInstance) {
  await warmYardBiasCoordinates();
  await registerDriverRoutes(app);
  await registerDriverLabelsRoutes(app);
  await registerDriverTagsRoutes(app);
  await registerDriversBulkRoutes(app);
  await registerDriversImportRoutes(app);
  await registerDriverHireDateApplyRoutes(app);
  await registerMdataAccountsRoutes(app);
  await registerMdataItemsRoutes(app);
  await registerDriverTeamRoutes(app);
  await registerDriverTeamSplitRoutes(app);
  await registerUnitsRoutes(app);
  await registerUnitBulkUpdateRoutes(app);
  await registerEquipmentBulkUpdateRoutes(app);
  await registerCustomerRoutes(app);
  await registerCustomerBulkRoutes(app);
  await registerCustomerFinancialSummaryRoutes(app);
  await registerCustomerInvoicesRoutes(app);
  await registerCustomerFinanceRollupRoutes(app);
  await registerVendorRoutes(app);
  await registerVendorPaymentMethodRoutes(app);
  await registerVendorRollupsRoutes(app);
  await registerVendorBulkRoutes(app);
  await registerLocationRoutes(app);
  await registerLoadRoutes(app);
  await registerLoadAbandonmentRoutes(app);
  await registerEquipmentRoutes(app);
  await registerEquipmentLogRoutes(app);
  await registerEquipmentTransferRoutes(app);
}
